# NOTE: Generated By HttpRunner v3.1.3
# FROM: TestCase/APICase/login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = Config("testcase description")

    teststeps = [
        Step(
            RunRequest("/api/service-upms/admin/user/login")
            .post(
                "https://test-member-api.heytea.com/api/service-upms/admin/user/login"
            )
            .with_headers(
                **{
                    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjgiLCJ1c2VyIjp7IndlY2hhdF91c2VyaWQiOm51bGwsImlkIjoiMTI4In0sImlhdCI6MTU4NDY4MzU4MiwibmJmIjoxNTg0NjgzNTgyLCJleHAiOjE1ODQ2OTA3ODIsImlzcyI6ImhleXRlYSJ9.TpCz9oY-beODSzcV7csHYjW4U8IYdPtAVnI_kHX2WBY",
                    "Content-Type": "application/json;charset=UTF-8",
                    "DNT": "1",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "cross-site",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_json({"password": "a12345678", "username": "admin"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
        ),
        Step(
            RunRequest("/api/service-upms/admin/nav/priv")
            .get("https://test-member-api.heytea.com/api/service-upms/admin/nav/priv")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjgiLCJ1c2VyIjp7IndlY2hhdF91c2VyaWQiOm51bGwsImlkIjoiMTI4In0sImlhdCI6MTU4NDY4ODQ4OSwibmJmIjoxNTg0Njg4NDg5LCJleHAiOjE1ODQ2OTU2ODksImlzcyI6ImhleXRlYSJ9.9VuZEHi3SQFL0VBh-FrSSUDMz3cIB42qqpu33xCrHG4",
                    "DNT": "1",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "cross-site",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
        ),
        Step(
            RunRequest("/static/media/bg.b4b4fa81.png")
            .get("http://test-member-console.heytea.com/static/media/bg.b4b4fa81.png")
            .with_headers(
                **{
                    "DNT": "1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "image/png")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
